# Generated by Django 5.2.7 on 2025-10-21 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_participating', to=settings.AUTH_USER_MODEL),
        ),
    ]
